name: Checkstyle

on:
  pull_request:
    branches:
      - main

jobs:
  checkstyle:
    name: Checkstyle
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Run Checkstyle
        run: |
          ./gradlew checkstyleMain
        working-directory: ${{ github.workspace }}

      - name: Fail Pull Request if Checkstyle fails
        if: ${{ failure() }}
        run: exit 1
