name: Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        
    - name: Set up Gradle
      uses: actions/setup-java@v2
      with:
        distribution: 'wrapper' 
        
    - name: Run Checkstyle
      run: ./gradlew checkstyleMain
